# Generated by Django 5.2.3 on 2025-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_trymailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trymailing',
            name='status',
            field=models.CharField(blank=True, choices=[('successful', 'Успешно'), ('no_successful', 'Не успешно')], max_length=15, null=True),
        ),
    ]
