# Generated by Django 5.2.3 on 2025-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_trymailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время первой отправки'),
        ),
    ]
