# Generated by Django 5.2.3 on 2025-06-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailing_owner_mailingrecipient_owner_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Can view mailing list and detail')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'permissions': [('can_view_mailing_recipient', 'Can view mailing recipient list and detail')], 'verbose_name': 'Получатель рассылки', 'verbose_name_plural': 'Получатели рассылок'},
        ),
    ]
