# Generated by Django 5.2.3 on 2025-06-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_mailing_options_alter_mailingrecipient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='can_used',
            field=models.BooleanField(default=True, verbose_name='Возможна отправка'),
        ),
    ]
